"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api/v1";

type View = "overview" | "energy" | "climate" | "anomalies" | "assistant" | "settings";
type WindowKey = "1h" | "6h" | "24h" | "7d" | "all";
type Point = Record<string, string | number | null> & { time: string };
type Anomaly = {
  id: string; code: string; category: string; severity: string; message: string;
  started_at: string; duration_minutes: number; observed: number | null;
  expected: number | null; residual: number | null; confidence: string;
  contributors: string[]; evidence_ids: string[]; active: boolean;
};
type Snapshot = {
  session_id: string; revision: number; cursor: string; playing: boolean; speed: number;
  window: WindowKey; site: {id:string; name:string; area_m2:number; growing_area_m2:number};
  quality: {state:string; backend:string; future_safe:boolean};
  data_version:string; definitions_version:string; model_version:string; evidence_ids:string[];
  kpis: Record<string, number | null>; latest: Record<string, number | null>;
  baseline: Record<string, any>; anomalies: Anomaly[]; climate_series: Point[];
  resource_series: Point[]; tariff:{configured:boolean;currency:string|null};
  metric_definitions: Record<string,{label:string;unit:string;source:string}>;
};
type AssistantResult = {
  answer:string; claims:{text:string;evidence_ids:string[]}[]; confidence:string;
  limitations:string[]; suggested_actions:string[]; model:string; evidence_version:string;
};

const views: {id:View; label:string; icon:string}[] = [
  {id:"overview",label:"Overview",icon:"◫"}, {id:"energy",label:"Energy & Resources",icon:"↯"},
  {id:"climate",label:"Operational Climate",icon:"⌁"}, {id:"anomalies",label:"Anomalies",icon:"△"},
  {id:"assistant",label:"Ask Varianz",icon:"✦"}, {id:"settings",label:"Settings",icon:"⚙"},
];

function fmt(value:number|null|undefined, digits=1){return value==null?"—":value.toLocaleString(undefined,{maximumFractionDigits:digits,minimumFractionDigits:digits});}
function date(value:string){return new Date(value).toLocaleString("en-CA",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});}
function Card({label,value,unit,meta,tone="green"}:{label:string;value:number|null|undefined;unit:string;meta:string;tone?:string}){
  return <article className={`metric-card ${tone}`}><div className="metric-top"><span>{label}</span><i/></div><strong>{fmt(value)} <small>{unit}</small></strong><p>{meta}</p></article>
}
type SeriesSpec={key:string;name:string;color:string;axis?:number;dashed?:boolean};
function LineChart({points,series,bands,height=360}:{points:Point[];series:SeriesSpec[];bands?:[number,number];height?:number}){
  const width=900,pad={left:58,right:58,top:42,bottom:38};
  const values=(axis:number)=>series.filter(s=>(s.axis||0)===axis).flatMap(s=>points.map(p=>p[s.key]).filter((v):v is number=>typeof v==="number"));
  const domain=(axis:number)=>{const v=values(axis);if(!v.length)return [0,1];let lo=Math.min(...v),hi=Math.max(...v);if(axis===0&&bands){lo=Math.min(lo,bands[0]);hi=Math.max(hi,bands[1])}const d=Math.max((hi-lo)*.1,.5);return [lo-d,hi+d]};
  const [lo,hi]=domain(0),[lo2,hi2]=domain(1),innerW=width-pad.left-pad.right,innerH=height-pad.top-pad.bottom;
  const y=(v:number,axis=0)=>pad.top+innerH-(v-(axis?lo2:lo))/Math.max((axis?hi2:hi)- (axis?lo2:lo),.001)*innerH;
  const x=(i:number)=>pad.left+i/Math.max(points.length-1,1)*innerW;
  const ticks=Array.from({length:5},(_,i)=>lo+(hi-lo)*i/4);
  const path=(s:SeriesSpec)=>points.map((p,i)=>typeof p[s.key]==="number"?`${i?"L":"M"}${x(i).toFixed(1)},${y(p[s.key] as number,s.axis||0).toFixed(1)}`:"").join(" ");
  if(!points.length)return <div className="no-data">No observations in this replay window.</div>;
  return <div className="line-chart"><div className="chart-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.name}</span>)}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={series.map(s=>s.name).join(" compared with ")}>
    {bands?<rect x={pad.left} y={y(bands[1])} width={innerW} height={Math.max(0,y(bands[0])-y(bands[1]))} fill="#63e6a510"/>:null}
    {ticks.map((t,i)=><g key={i}><line x1={pad.left} x2={width-pad.right} y1={y(t)} y2={y(t)} stroke="#1d332b"/><text x={pad.left-8} y={y(t)+4} textAnchor="end">{t.toFixed(1)}</text></g>)}
    <line x1={pad.left} x2={pad.left} y1={pad.top} y2={height-pad.bottom} stroke="#355047"/><line x1={pad.left} x2={width-pad.right} y1={height-pad.bottom} y2={height-pad.bottom} stroke="#355047"/>
    {series.map(s=><path key={s.key} d={path(s)} fill="none" stroke={s.color} strokeWidth="2.2" strokeDasharray={s.dashed?"7 6":undefined}><title>{s.name}</title></path>)}
    <text x={pad.left} y={height-9}>{date(points[0].time)}</text><text x={width-pad.right} y={height-9} textAnchor="end">{date(points[points.length-1].time)}</text>
  </svg></div>
}

export default function Dashboard(){
  const [view,setView]=useState<View>("overview"),[windowKey,setWindowKey]=useState<WindowKey>("24h");
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const [question,setQuestion]=useState("What requires operator attention at this replay cursor?");
  const [assistant,setAssistant]=useState<AssistantResult|null>(null),[asking,setAsking]=useState(false),[focus,setFocus]=useState<string|null>(null);
  const requestRef=useRef<AbortController|null>(null);

  const refresh=useCallback(async(id:string,windowValue:WindowKey=windowKey)=>{
    requestRef.current?.abort(); const controller=new AbortController(); requestRef.current=controller;
    const next:Snapshot=await fetch(`${API}/replay-sessions/${id}/overview?window=${windowValue}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error("Analytics API unavailable");return r.json()});
    setData(current=>!current||next.revision>=current.revision?next:current); setError(""); setLoading(false);
  },[windowKey]);
  const create=useCallback(async()=>{try{setLoading(true);const s=await fetch(`${API}/replay-sessions`,{method:"POST"}).then(r=>r.json());await refresh(s.id)}catch(e){setError(e instanceof Error?e.message:"API unavailable");setLoading(false)}},[refresh]);
  useEffect(()=>{create()},[]);
  useEffect(()=>{if(!data?.playing)return;const timer=setInterval(()=>refresh(data.session_id),2000);return()=>clearInterval(timer)},[data?.playing,data?.session_id,refresh]);
  async function mutate(action:string,value?:number|string){if(!data)return;const s=await fetch(`${API}/replay-sessions/${data.session_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,expected_revision:data.revision,value})}).then(r=>{if(!r.ok)throw new Error("Replay revision conflict");return r.json()});await refresh(s.id)}
  async function changeWindow(next:WindowKey){setWindowKey(next);if(data)await refresh(data.session_id,next)}
  async function ask(custom?:string,anomalyId?:string){if(!data)return;setAsking(true);setView("assistant");setFocus(anomalyId||null);const prompt=custom||question;setQuestion(prompt);try{const result=await fetch(`${API}/replay-sessions/${data.session_id}/assistant/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:prompt,anomaly_id:anomalyId})});if(!result.ok)throw new Error("Varianz AI could not complete the explanation");setAssistant(await result.json());setError("")}catch(e){setError(e instanceof Error?e.message:"Assistant unavailable")}finally{setAsking(false)}}
  const k=data?.kpis||{}; const baseline=data?.baseline||{}; const top=data?.anomalies?.[0];

  return <div className="app-shell">
    <aside className="sidebar"><div className="logo"><span>V</span><div><b>VARIANZ</b><small>Operational Intelligence</small></div></div><nav>{views.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><i>{item.icon}</i>{item.label}{item.id==="anomalies"&&Number(k.active_anomalies)>0?<em>{k.active_anomalies}</em>:null}</button>)}</nav><div className="side-foot"><span className="status-dot"/>Supabase connected<small>Decision support only</small></div></aside>
    <main className="workspace">
      <header className="topbar"><div><span className="eyebrow">WAGENINGEN REFERENCE · GREENHOUSE 01</span><h1>{views.find(v=>v.id===view)?.label}</h1></div><div className="replay"><div><b>LIVE SIMULATION</b><span>{data?date(data.cursor):"Loading…"}</span></div><button aria-label="Play replay" onClick={()=>mutate("play")} className={data?.playing?"selected":""}>▶</button><button aria-label="Pause replay" onClick={()=>mutate("pause")}>Ⅱ</button><select aria-label="Replay speed" value={data?.speed||1} onChange={e=>mutate("speed",Number(e.target.value))}><option value="1">1×</option><option value="5">5×</option><option value="20">20×</option><option value="60">60×</option></select><button className="event-jump" onClick={()=>mutate("seek","2020-05-20T12:00:00Z")}>Natural event</button><button aria-label="Reset replay" onClick={()=>mutate("reset")}>↺</button></div></header>
      <section className="context-bar"><div><span className={`quality ${data?.quality.state}`}>{data?.quality.state||"loading"}</span><span>Source: {data?.quality.backend||"—"}</span><span>Model: {data?.model_version||"—"}</span></div><div className="window-picker">{(["1h","6h","24h","7d","all"] as WindowKey[]).map(w=><button key={w} className={windowKey===w?"active":""} onClick={()=>changeWindow(w)}>{w}</button>)}</div></section>
      {error?<section className="error-banner">{error}<button onClick={()=>setError("")}>×</button></section>:null}
      {loading?<div className="loading"><span/>Building point-in-time analytics…</div>:null}
      {!loading&&data&&view==="overview"?<>
        <section className="hero-grid">
          <Card label="Total energy" value={k.daily_total_energy_mj_m2} unit="MJ/m²·day" meta={`${fmt(k.daily_heat_mj_m2)} heat · ${fmt(k.daily_electricity_kwh_m2)} kWh electricity`}/>
          <Card label="Heat vs expected" value={baseline.residual_mj_m2} unit="MJ/m²" meta={baseline.status==="ready"?`${baseline.variance_pct>0?"Above":"Below"} ${baseline.selected_model} baseline · ${baseline.confidence} confidence`:"Baseline building — minimum 45 days"} tone={baseline.anomaly?"amber":"green"}/>
          <Card label="Climate compliance" value={k.climate_compliance_24h_pct} unit="% / 24h" meta={`${fmt(k.climate_compliance_1h_pct)}% last hour · ${fmt(k.anomaly_minutes,0)} anomaly min`} tone={Number(k.climate_compliance_24h_pct)<90?"amber":"green"}/>
          <Card label="Drain ratio" value={k.drain_ratio_pct} unit="%" meta={`${fmt(k.daily_irrigation_l_m2)} L/m² irrigation · ${fmt(k.daily_drain_l_m2)} L/m² drain`} tone={Number(k.drain_ratio_pct)>80||Number(k.drain_ratio_pct)<10?"amber":"green"}/>
          <Card label="Operating cost" value={k.operating_cost_cad_m2} unit="CAD/m²·day" meta={data.tariff.configured?"Ontario tariff profile applied":"Configure Ontario tariffs to enable cost"} tone="neutral"/>
        </section>
        <section className="overview-grid"><article className="panel span-2"><div className="panel-head"><div><span>OPERATIONAL CLIMATE</span><h2>Inside temperature vs targets</h2></div><button onClick={()=>setView("climate")}>Open climate →</button></div><LineChart points={data.climate_series} series={[{key:"Tair",name:"Indoor °C",color:"#63e6a5"},{key:"Tout",name:"Outdoor °C",color:"#70a4ff"},{key:"t_heat_vip",name:"Heat target °C",color:"#f0b45a",dashed:true},{key:"t_ventlee_vip",name:"Vent target °C",color:"#d178ff",dashed:true}]} bands={[18,26]}/></article>
          <article className="panel attention"><div className="panel-head"><div><span>OPERATOR ATTENTION</span><h2>{top?top.message:"Operation within configured review bands"}</h2></div></div>{top?<><div className={`severity ${top.severity}`}>{top.severity} · {top.duration_minutes} min</div><dl><div><dt>Observed</dt><dd>{fmt(top.observed)}</dd></div><div><dt>Expected</dt><dd>{fmt(top.expected)}</dd></div><div><dt>Confidence</dt><dd>{top.confidence}</dd></div></dl><button className="primary" onClick={()=>ask(`Explain anomaly ${top.code}, its operational impact, and the safest next checks.`,top.id)}>✦ Explain with Varianz</button></>:<p>No active anomaly requires intervention at this cursor.</p>}</article>
        </section>
        <section className="model-strip"><div><span>BASELINE STATUS</span><b>{baseline.status==="ready"?(baseline.candidate_promoted?"Elastic Net promoted":"Naive baseline retained"):"Collecting training history"}</b></div><div><span>LOCKED TEST</span><b>{baseline.promotion_gate?`${fmt(baseline.promotion_gate.locked_test_improvement_pct)}% vs naive`:"Not available"}</b></div><div><span>UNCERTAINTY</span><b>{baseline.p10_mj_m2!=null?`${fmt(baseline.p10_mj_m2)}–${fmt(baseline.p90_mj_m2)} MJ/m²`:"Not available"}</b></div><div><span>EVIDENCE</span><b>{data.evidence_ids.length} linked records</b></div></section>
      </>:null}
      {!loading&&data&&view==="energy"?<><section className="hero-grid compact"><Card label="Heat" value={k.daily_heat_mj_m2} unit="MJ/m²·day" meta="Observed daily resource total"/><Card label="Electricity" value={k.daily_electricity_kwh_m2} unit="kWh/m²·day" meta={`${fmt(k.peak_electricity_share_pct)}% peak share`}/><Card label="CO₂" value={k.daily_co2_kg_m2} unit="kg/m²·day" meta="Observed resource intensity"/><Card label="Water" value={k.daily_irrigation_l_m2} unit="L/m²·day" meta={`${fmt(k.drain_ratio_pct)}% drain ratio`}/></section><section className="two-col"><article className="panel"><div className="panel-head"><div><span>ENERGY INTENSITY</span><h2>Heat and electricity — last 30 days</h2></div></div><LineChart height={390} points={data.resource_series} series={[{key:"Heat_cons",name:"Heat MJ/m²",color:"#f0b45a"},{key:"ElecHigh",name:"Peak kWh/m²",color:"#63e6a5",axis:1},{key:"ElecLow",name:"Off-peak kWh/m²",color:"#70a4ff",axis:1}]}/></article><article className="panel baseline-card"><span>WEATHER-NORMALIZED BASELINE</span><h2>{baseline.status==="ready"?`${fmt(baseline.actual_mj_m2)} actual vs ${fmt(baseline.expected_mj_m2)} expected`:"Insufficient history at cursor"}</h2><div className="baseline-bar"><i style={{width:`${Math.min(100,Math.max(0,(baseline.actual_mj_m2||0)/Math.max(baseline.p90_mj_m2||6,1)*100))}%`}}/></div><p>Selected: <b>{baseline.selected_model||"pending"}</b></p><p>Promotion: <b>{baseline.candidate_promoted?"passed":"candidate not promoted"}</b></p><p>Confidence: <b>{baseline.confidence||"not available"}</b></p><button className="primary" onClick={()=>ask("Explain today's energy intensity, the baseline result, uncertainty, and likely operational drivers.")}>✦ Explain energy status</button></article></section><article className="panel"><div className="panel-head"><div><span>WATER BALANCE</span><h2>Irrigation and drain</h2></div></div><LineChart height={310} points={data.resource_series} series={[{key:"Irr",name:"Irrigation L/m²",color:"#70a4ff"},{key:"Drain",name:"Drain L/m²",color:"#63e6a5"}]}/></article></>:null}
      {!loading&&data&&view==="climate"?<><section className="hero-grid compact"><Card label="Indoor temperature" value={data.latest.Tair} unit="°C" meta={`Outdoor ${fmt(data.latest.Tout)} °C`}/><Card label="Relative humidity" value={data.latest.Rhair} unit="%" meta={`${fmt(k.climate_compliance_1h_pct)}% compliance / 1h`}/><Card label="Humidity deficit" value={data.latest.HumDef} unit="g/m³" meta="Observed indoor state"/><Card label="CO₂" value={data.latest.CO2air} unit="ppm" meta="Observed concentration"/></section><article className="panel"><div className="panel-head"><div><span>CONTROL PERFORMANCE</span><h2>Temperature, setpoints and safe band</h2></div></div><LineChart height={430} points={data.climate_series} series={[{key:"Tair",name:"Indoor °C",color:"#63e6a5"},{key:"Tout",name:"Outdoor °C",color:"#70a4ff"},{key:"t_heat_vip",name:"Heat target °C",color:"#f0b45a",dashed:true},{key:"t_ventlee_vip",name:"Vent target °C",color:"#d178ff",dashed:true}]} bands={[18,26]}/></article><section className="two-col"><article className="panel"><div className="panel-head"><div><span>HUMIDITY</span><h2>RH and humidity deficit</h2></div></div><LineChart height={330} points={data.climate_series} series={[{key:"Rhair",name:"RH %",color:"#70a4ff"},{key:"HumDef",name:"Deficit g/m³",color:"#f0b45a",axis:1}]}/></article><article className="panel"><div className="panel-head"><div><span>ACTUATION</span><h2>Screens and vents</h2></div></div><LineChart height={330} points={data.climate_series} series={[{key:"EnScr",name:"Energy screen %",color:"#d178ff"},{key:"VentLee",name:"Leeward vent %",color:"#63e6a5"}]}/></article></section></>:null}
      {!loading&&data&&view==="anomalies"?<section className="anomaly-layout"><article className="panel"><div className="panel-head"><div><span>NATURAL EVENTS ONLY</span><h2>Operational deviations · last 7 days</h2></div><b>{data.anomalies.length} events</b></div><div className="anomaly-list">{data.anomalies.length?data.anomalies.map(a=><button key={a.id} onClick={()=>setFocus(a.id)} className={focus===a.id?"selected":""}><i className={`severity-dot ${a.severity}`}/><div><b>{a.message}</b><span>{date(a.started_at)} · {a.duration_minutes} min · {a.category}</span></div><em>{a.active?"ACTIVE":"CLOSED"}</em></button>):<p>No natural deviations detected in this window.</p>}</div></article><article className="panel detail">{(()=>{const a=data.anomalies.find(x=>x.id===focus)||data.anomalies[0];return a?<><span>ANOMALY EVIDENCE</span><h2>{a.code.replaceAll("_"," ")}</h2><div className={`severity ${a.severity}`}>{a.severity} severity</div><dl><div><dt>Duration</dt><dd>{a.duration_minutes} min</dd></div><div><dt>Observed</dt><dd>{fmt(a.observed)}</dd></div><div><dt>Expected</dt><dd>{fmt(a.expected)}</dd></div><div><dt>Confidence</dt><dd>{a.confidence}</dd></div></dl><h3>Contributing signals</h3><div className="chips">{a.contributors.map(c=><span key={c}>{c}</span>)}</div><button className="primary" onClick={()=>ask(`Explain ${a.code}, quantify the deviation, and recommend operator checks without claiming causality.`,a.id)}>✦ Explain this deviation</button></>:<><h2>No event selected</h2><p>Advance the replay or widen the window to inspect natural deviations.</p></>})()}</article></section>:null}
      {!loading&&data&&view==="assistant"?<section className="assistant-layout"><article className="panel assistant-main"><div className="assistant-title"><span>✦</span><div><b>VARIANZ AI</b><h2>Operational interpretation grounded in evidence</h2></div></div><form onSubmit={(e)=>{e.preventDefault();ask()}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about energy, climate, resources or an anomaly…"/><button className="primary" disabled={asking}>{asking?"Analyzing evidence…":"Ask Varianz →"}</button></form>{assistant?<div className="answer"><div className="answer-meta"><span>{assistant.confidence} confidence</span><span>{assistant.model}</span><span>definitions {assistant.evidence_version}</span></div><p>{assistant.answer}</p><h3>Evidence-backed claims</h3>{assistant.claims.map((claim,i)=><div className="claim" key={i}><p>{claim.text}</p><div className="chips">{claim.evidence_ids.map(id=><span key={id}>{id}</span>)}</div></div>)}<h3>Suggested operator checks</h3><ul>{assistant.suggested_actions.map((x,i)=><li key={i}>{x}</li>)}</ul>{assistant.limitations.length?<div className="limitations"><b>Limitations</b>{assistant.limitations.map((x,i)=><p key={i}>{x}</p>)}</div>:null}</div>:<div className="assistant-empty"><b>Try a grounded question</b><button onClick={()=>{setQuestion("Why is heat intensity different from the expected baseline?");}}>Why is heat different from expected?</button><button onClick={()=>{setQuestion("Which climate deviation requires attention now?");}}>What requires attention now?</button><button onClick={()=>{setQuestion("Summarize resource efficiency for an investor without claiming savings.");}}>Summarize resource efficiency</button></div>}</article><aside className="panel evidence-drawer"><span>VISIBLE EVIDENCE</span><h3>Replay context</h3><p>{date(data.cursor)}</p><h3>Versions</h3><p>{data.data_version}</p><p>{data.model_version}</p><h3>Evidence IDs</h3><div className="chips vertical">{data.evidence_ids.map(id=><span key={id}>{id}</span>)}</div></aside></section>:null}
      {!loading&&data&&view==="settings"?<Settings siteId={data.site.id} onSaved={()=>refresh(data.session_id)}/>:null}
    </main>
  </div>
}

function Settings({siteId,onSaved}:{siteId:string;onSaved:()=>void}){
  const [saved,setSaved]=useState(""),[form,setForm]=useState({currency:"CAD",effective_from:"2019-12-16",electricity_peak_per_kwh:"",electricity_offpeak_per_kwh:"",heat_per_mj:"",co2_per_kg:"",water_per_m3:"",source:""});
  async function submit(e:FormEvent){e.preventDefault();const payload={...form,electricity_peak_per_kwh:Number(form.electricity_peak_per_kwh),electricity_offpeak_per_kwh:Number(form.electricity_offpeak_per_kwh),heat_per_mj:Number(form.heat_per_mj),co2_per_kg:Number(form.co2_per_kg),water_per_m3:Number(form.water_per_m3)};const r=await fetch(`${API}/sites/${siteId}/tariff-profile`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setSaved(r.ok?"Ontario tariff profile saved and versioned.":"Tariff profile could not be saved.");if(r.ok)onSaved()}
  return <section className="settings-grid"><article className="panel"><span>ONTARIO ECONOMICS</span><h2>Tariff profile</h2><p>Costs remain hidden until every input has a reviewed value and source. Varianz never substitutes Challenge 2020 prices.</p><form className="settings-form" onSubmit={submit}><label>Currency<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label>Effective from<input type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label><label>Peak electricity <small>CAD/kWh</small><input required type="number" step="any" value={form.electricity_peak_per_kwh} onChange={e=>setForm({...form,electricity_peak_per_kwh:e.target.value})}/></label><label>Off-peak electricity <small>CAD/kWh</small><input required type="number" step="any" value={form.electricity_offpeak_per_kwh} onChange={e=>setForm({...form,electricity_offpeak_per_kwh:e.target.value})}/></label><label>Heat <small>CAD/MJ</small><input required type="number" step="any" value={form.heat_per_mj} onChange={e=>setForm({...form,heat_per_mj:e.target.value})}/></label><label>CO₂ <small>CAD/kg</small><input required type="number" step="any" value={form.co2_per_kg} onChange={e=>setForm({...form,co2_per_kg:e.target.value})}/></label><label>Water <small>CAD/m³</small><input required type="number" step="any" value={form.water_per_m3} onChange={e=>setForm({...form,water_per_m3:e.target.value})}/></label><label className="wide">Source / evidence<input required value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Utility tariff document or approved assumption"/></label><button className="primary wide">Save versioned tariff</button></form>{saved?<p className="saved">{saved}</p>:null}</article><aside className="panel policy"><span>POLICY</span><h2>Cost display guardrails</h2><ul><li>No default tariff values</li><li>Currency and units always visible</li><li>Effective date controls replay eligibility</li><li>Source retained for evidence</li><li>No savings claims in Varianz 0.2</li></ul></aside></section>
}
