"use client";
import { useEffect, useState } from "react";
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api/v1";
type Point = { time: string; Tair?: number; Tout?: number };
type Payload = { session_id:string; revision:number; cursor:string; playing:boolean; speed:number; kpis:Record<string,number>; baseline:Record<string,unknown>; alerts:{code:string;message:string}[]; climate_series:Point[] };
function Chart({data}:{data:Point[]}) { const vals=data.flatMap(p=>[p.Tair,p.Tout]).filter((v):v is number=>typeof v==="number"); if(!vals.length)return <div className="chart">No observations at this cursor.</div>; const lo=Math.min(...vals)-1,hi=Math.max(...vals)+1,w=800,h=230; const path=(k:"Tair"|"Tout")=>data.map((p,i)=>`${i?"L":"M"}${i/(data.length-1||1)*w},${h-((p[k]??lo)-lo)/(hi-lo)*h}`).join(" "); return <div className="chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Inside and outside temperature"><path d={path("Tair")} className="inside"/><path d={path("Tout")} className="outside"/></svg><div className="legend">Green: inside · Amber: outside</div></div> }
export default function Dashboard(){
  const [data,setData]=useState<Payload|null>(null),[error,setError]=useState("");
  async function refresh(id:string){const next:Payload=await fetch(`${API}/replay-sessions/${id}/dashboard`).then(r=>r.json());setData(current=>!current||next.revision>=current.revision?next:current)}
  async function create(){try{const s=await fetch(`${API}/replay-sessions`,{method:"POST"}).then(r=>r.json());await refresh(s.id)}catch{setError("API unavailable. Start FastAPI locally.")}}
  async function mutate(action:string,value?:number){if(!data)return;const s=await fetch(`${API}/replay-sessions/${data.session_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,expected_revision:data.revision,value})}).then(r=>r.json());await refresh(s.id)}
  useEffect(()=>{create()},[]);
  useEffect(()=>{if(!data?.playing)return;const timer=setInterval(()=>refresh(data.session_id),2000);return()=>clearInterval(timer)},[data?.playing,data?.session_id]);
  const k=data?.kpis;
  return <main><header><div><span className="brand">VARIANZ</span><h1>Greenhouse Overview</h1></div><div className="clock"><b>LIVE SIMULATION</b><span>{data?new Date(data.cursor).toLocaleString():"Loading…"}</span><button onClick={()=>mutate("play")}>Play</button><button onClick={()=>mutate("pause")}>Pause</button><select value={data?.speed||1} onChange={e=>mutate("speed",Number(e.target.value))}><option value="1">1×</option><option value="5">5×</option><option value="20">20×</option><option value="60">60×</option></select></div></header><section className="notice">Wageningen research dataset · Decision support only · No equipment control</section>{error&&<section className="error">{error} <button onClick={create}>Retry</button></section>}<section className="grid">{[["Total energy",k?.daily_total_energy_mj_m2,"MJ/m²"],["Climate compliance",k?.climate_compliance_pct,"%"],["Active anomalies",k?.active_anomalies,"events"],["Daily heat",k?.daily_heat_mj_m2,"MJ/m²"]].map(([a,b,c])=><article key={String(a)}><small>Observed / calculated</small><h2>{b??"—"} <i>{c}</i></h2><p>{a}</p></article>)}</section><section className="panels"><article><h2>Inside vs outside temperature</h2><Chart data={data?.climate_series||[]}/></article><article><h2>Operational insights</h2>{data?.alerts.length?data.alerts.map(a=><p className="alert" key={a.code}>{a.message}</p>):<p>No active deterministic alerts.</p>}<p>Baseline: {String(data?.baseline.status||"not available")}</p><button className="primary" disabled>Scenario optimization · next stage</button></article></section></main>
}
