import { AssistantResult, Snapshot } from "../lib/types";
import { date } from "../lib/format";

type AssistantProps = {
  data:Snapshot; question:string; setQuestion:(q:string)=>void;
  assistant:AssistantResult|null; asking:boolean; ask:(custom?:string,anomalyId?:string)=>void;
};

export function AssistantView({data,question,setQuestion,assistant,asking,ask}:AssistantProps){
  return <section className="assistant-layout"><article className="panel assistant-main"><div className="assistant-title"><span>✦</span><div><b>VARIANZ AI</b><h2>Operational interpretation grounded in evidence</h2></div></div><form onSubmit={(e)=>{e.preventDefault();ask()}}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about energy, climate, resources or an anomaly…"/><button className="primary" disabled={asking||question.trim().length<3}>{asking?"Analyzing evidence…":"Ask Varianz →"}</button></form>{assistant?<div className="answer"><div className="answer-meta"><span>{assistant.confidence} confidence</span><span>{assistant.model}</span><span>definitions {assistant.evidence_version}</span></div><p>{assistant.answer}</p><h3>Evidence-backed claims</h3>{assistant.claims.map((claim,i)=><div className="claim" key={i}><p>{claim.text}</p><div className="chips">{claim.evidence_ids.map(id=><span key={id}>{id}</span>)}</div></div>)}<h3>Suggested operator checks</h3><ul>{assistant.suggested_actions.map((x,i)=><li key={i}>{x}</li>)}</ul>{assistant.limitations.length?<div className="limitations"><b>Limitations</b>{assistant.limitations.map((x,i)=><p key={i}>{x}</p>)}</div>:null}</div>:<div className="assistant-empty"><b>Try a grounded question</b><button onClick={()=>{setQuestion("Why is heat intensity different from the expected baseline?");}}>Why is heat different from expected?</button><button onClick={()=>{setQuestion("Which climate deviation requires attention now?");}}>What requires attention now?</button><button onClick={()=>{setQuestion("Summarize resource efficiency for an investor without claiming savings.");}}>Summarize resource efficiency</button></div>}</article><aside className="panel evidence-drawer"><span>VISIBLE EVIDENCE</span><h3>Replay context</h3><p>{date(data.cursor)}</p><h3>Versions</h3><p>{data.data_version}</p><p>{data.model_version}</p><h3>Evidence IDs</h3><div className="chips vertical">{data.evidence_ids.map(id=><span key={id}>{id}</span>)}</div></aside></section>
}
