import { FormEvent, useEffect, useState } from "react";

type TouWindow={label:"peak"|"midpeak"|"offpeak";days:"mon-fri"|"all";start:string;end:string;season:"summer"|"winter"|"all"};
type FormState={currency:string;effective_from:string;electricity_peak_per_kwh:string;electricity_midpeak_per_kwh:string;electricity_offpeak_per_kwh:string;heat_per_mj:string;co2_per_kg:string;water_per_m3:string;source:string;preset:string;tou_windows:TouWindow[]};

const schedules:Record<string,TouWindow[]>={
  "Ontario regulated TOU · seasonal":[
    {label:"midpeak",days:"mon-fri",season:"summer",start:"07:00",end:"11:00"},
    {label:"peak",days:"mon-fri",season:"summer",start:"11:00",end:"17:00"},
    {label:"midpeak",days:"mon-fri",season:"summer",start:"17:00",end:"19:00"},
    {label:"peak",days:"mon-fri",season:"winter",start:"07:00",end:"11:00"},
    {label:"midpeak",days:"mon-fri",season:"winter",start:"11:00",end:"17:00"},
    {label:"peak",days:"mon-fri",season:"winter",start:"17:00",end:"19:00"},
  ],
};
const OEB_SOURCE="https://www.oeb.ca/consumer-information-and-protection/electricity-rates";
const initial:FormState={currency:"CAD",effective_from:"2019-12-16",electricity_peak_per_kwh:"",electricity_midpeak_per_kwh:"",electricity_offpeak_per_kwh:"",heat_per_mj:"",co2_per_kg:"",water_per_m3:"",source:"",preset:"",tou_windows:[]};

export function SettingsView({siteId,onSaved,apiFetch}:{siteId:string;onSaved:()=>void;apiFetch:(path:string,init?:RequestInit)=>Promise<Response>}){
  const [saved,setSaved]=useState(""),[form,setForm]=useState<FormState>(initial);
  useEffect(()=>{let active=true;apiFetch(`/sites/${siteId}/tariff-profile`).then(async response=>response.ok?response.json():null).then(result=>{const profile=result?.profile;if(!active||!profile)return;const text=(value:number|null|undefined)=>value==null?"":String(value);setForm({currency:profile.currency,effective_from:profile.effective_from,electricity_peak_per_kwh:text(profile.electricity_peak_per_kwh),electricity_midpeak_per_kwh:text(profile.electricity_midpeak_per_kwh),electricity_offpeak_per_kwh:text(profile.electricity_offpeak_per_kwh),heat_per_mj:text(profile.heat_per_mj),co2_per_kg:text(profile.co2_per_kg),water_per_m3:text(profile.water_per_m3),source:profile.source,preset:profile.preset||"Custom reviewed schedule",tou_windows:(profile.tou_windows||[]).map((item:TouWindow)=>({...item,season:item.season||"all"}))})}).catch(()=>undefined);return()=>{active=false}},[apiFetch,siteId]);
  function chooseSchedule(name:string){setForm(current=>({...current,preset:name,tou_windows:schedules[name]||current.tou_windows,source:current.source||OEB_SOURCE}))}
  async function submit(e:FormEvent){e.preventDefault();if(!form.tou_windows.length){setSaved("Select and review a time-of-use schedule before saving.");return}const optionalNumber=(value:string)=>value.trim()===""?null:Number(value);const payload={...form,electricity_peak_per_kwh:optionalNumber(form.electricity_peak_per_kwh),electricity_midpeak_per_kwh:optionalNumber(form.electricity_midpeak_per_kwh),electricity_offpeak_per_kwh:optionalNumber(form.electricity_offpeak_per_kwh),heat_per_mj:optionalNumber(form.heat_per_mj),co2_per_kg:optionalNumber(form.co2_per_kg),water_per_m3:optionalNumber(form.water_per_m3)};const r=await apiFetch(`/sites/${siteId}/tariff-profile`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setSaved(r.ok?"Ontario seasonal TOU schedule saved. On-, mid- and off-peak allocation is enabled; cost appears only when every rate is complete.":"Tariff profile could not be saved.");if(r.ok)onSaved()}
  return <section className="settings-grid"><article className="panel"><span>ONTARIO ECONOMICS</span><h2>Tariff profile and time-of-use schedule</h2><p>A sourced schedule enables on-, mid- and off-peak allocation. Monetary rates remain optional and enable cost only when every field is complete.</p><form className="settings-form" onSubmit={submit}>
    <label>Currency<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label>Effective from<input type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label>
    <label className="wide">Schedule preset<select required value={form.preset} onChange={e=>chooseSchedule(e.target.value)}><option value="">Select a reviewed schedule</option>{form.preset&&!schedules[form.preset]?<option value={form.preset}>{form.preset}</option>:null}{Object.keys(schedules).map(name=><option key={name}>{name}</option>)}</select></label>
    {form.tou_windows.length?<div className="wide schedule-preview"><b>Seasonal weekday windows</b>{form.tou_windows.map((item,index)=><span key={`${item.season}-${item.label}-${item.start}-${index}`}>{item.season} · {item.label==="peak"?"on-peak":item.label} · {item.start}–{item.end}</span>)}<small>Off-peak: 7 p.m.–7 a.m. on weekdays and all day on weekends and Ontario TOU holidays. Summer is May–October; winter is November–April.</small></div>:null}
    <label>On-peak electricity <small>CAD/kWh · optional</small><input min="0" type="number" step="any" value={form.electricity_peak_per_kwh} onChange={e=>setForm({...form,electricity_peak_per_kwh:e.target.value})}/></label><label>Mid-peak electricity <small>CAD/kWh · optional</small><input min="0" type="number" step="any" value={form.electricity_midpeak_per_kwh} onChange={e=>setForm({...form,electricity_midpeak_per_kwh:e.target.value})}/></label><label>Off-peak electricity <small>CAD/kWh · optional</small><input min="0" type="number" step="any" value={form.electricity_offpeak_per_kwh} onChange={e=>setForm({...form,electricity_offpeak_per_kwh:e.target.value})}/></label><label>Heat <small>CAD/MJ · optional</small><input min="0" type="number" step="any" value={form.heat_per_mj} onChange={e=>setForm({...form,heat_per_mj:e.target.value})}/></label><label>CO₂ <small>CAD/kg · optional</small><input min="0" type="number" step="any" value={form.co2_per_kg} onChange={e=>setForm({...form,co2_per_kg:e.target.value})}/></label><label>Water <small>CAD/m³ · optional</small><input min="0" type="number" step="any" value={form.water_per_m3} onChange={e=>setForm({...form,water_per_m3:e.target.value})}/></label><label className="wide">Source / evidence<input required value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Utility tariff document or approved assumption"/></label><button className="primary wide">Save versioned schedule</button></form>{saved?<p className="saved">{saved}</p>:null}</article><aside className="panel policy"><span>POLICY</span><h2>Cost display guardrails</h2><ul><li>Schedule enables on/mid/off-peak shares without prices</li><li>Season and Ontario holidays are applied automatically</li><li>No default tariff values</li><li>Cost requires every rate</li><li>Effective date controls replay eligibility</li><li>Source retained for evidence</li></ul></aside></section>
}
