import { FormEvent, useEffect, useState } from "react";

type TouWindow={label:"peak";days:"mon-fri"|"all";start:string;end:string};
type FormState={currency:string;effective_from:string;electricity_peak_per_kwh:string;electricity_offpeak_per_kwh:string;heat_per_mj:string;co2_per_kg:string;water_per_m3:string;source:string;preset:string;tou_windows:TouWindow[]};

const schedules:Record<string,TouWindow[]>={
  "Ontario winter · schedule only":[{label:"peak",days:"mon-fri",start:"07:00",end:"11:00"},{label:"peak",days:"mon-fri",start:"17:00",end:"19:00"}],
  "Ontario summer · schedule only":[{label:"peak",days:"mon-fri",start:"11:00",end:"17:00"}],
};
const initial:FormState={currency:"CAD",effective_from:"2019-12-16",electricity_peak_per_kwh:"",electricity_offpeak_per_kwh:"",heat_per_mj:"",co2_per_kg:"",water_per_m3:"",source:"",preset:"",tou_windows:[]};

export function SettingsView({siteId,onSaved,apiFetch}:{siteId:string;onSaved:()=>void;apiFetch:(path:string,init?:RequestInit)=>Promise<Response>}){
  const [saved,setSaved]=useState(""),[form,setForm]=useState<FormState>(initial);
  useEffect(()=>{let active=true;apiFetch(`/sites/${siteId}/tariff-profile`).then(async response=>response.ok?response.json():null).then(result=>{const profile=result?.profile;if(!active||!profile)return;setForm({currency:profile.currency,effective_from:profile.effective_from,electricity_peak_per_kwh:String(profile.electricity_peak_per_kwh),electricity_offpeak_per_kwh:String(profile.electricity_offpeak_per_kwh),heat_per_mj:String(profile.heat_per_mj),co2_per_kg:String(profile.co2_per_kg),water_per_m3:String(profile.water_per_m3),source:profile.source,preset:profile.preset||"Custom reviewed schedule",tou_windows:profile.tou_windows||[]})}).catch(()=>undefined);return()=>{active=false}},[apiFetch,siteId]);
  function chooseSchedule(name:string){setForm(current=>({...current,preset:name,tou_windows:schedules[name]||current.tou_windows}))}
  async function submit(e:FormEvent){e.preventDefault();if(!form.tou_windows.length){setSaved("Select and review a time-of-use schedule before saving.");return}const payload={...form,electricity_peak_per_kwh:Number(form.electricity_peak_per_kwh),electricity_offpeak_per_kwh:Number(form.electricity_offpeak_per_kwh),heat_per_mj:Number(form.heat_per_mj),co2_per_kg:Number(form.co2_per_kg),water_per_m3:Number(form.water_per_m3)};const r=await apiFetch(`/sites/${siteId}/tariff-profile`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setSaved(r.ok?"Ontario tariff profile saved and versioned.":"Tariff profile could not be saved.");if(r.ok)onSaved()}
  return <section className="settings-grid"><article className="panel"><span>ONTARIO ECONOMICS</span><h2>Tariff profile and time-of-use schedule</h2><p>Schedule presets never populate rates. Verify the applicable utility schedule, enter reviewed rates, and retain the source as evidence.</p><form className="settings-form" onSubmit={submit}>
    <label>Currency<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label>Effective from<input type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label>
    <label className="wide">Schedule preset<select required value={form.preset} onChange={e=>chooseSchedule(e.target.value)}><option value="">Select a reviewed schedule</option>{Object.keys(schedules).map(name=><option key={name}>{name}</option>)}</select></label>
    {form.tou_windows.length?<div className="wide schedule-preview"><b>Peak windows</b>{form.tou_windows.map((item,index)=><span key={`${item.start}-${index}`}>{item.days} · {item.start}–{item.end}</span>)}<small>Off-peak is the complement. Verify this schedule against the effective date and utility source.</small></div>:null}
    <label>Peak electricity <small>CAD/kWh</small><input required min="0" type="number" step="any" value={form.electricity_peak_per_kwh} onChange={e=>setForm({...form,electricity_peak_per_kwh:e.target.value})}/></label><label>Off-peak electricity <small>CAD/kWh</small><input required min="0" type="number" step="any" value={form.electricity_offpeak_per_kwh} onChange={e=>setForm({...form,electricity_offpeak_per_kwh:e.target.value})}/></label><label>Heat <small>CAD/MJ</small><input required min="0" type="number" step="any" value={form.heat_per_mj} onChange={e=>setForm({...form,heat_per_mj:e.target.value})}/></label><label>CO₂ <small>CAD/kg</small><input required min="0" type="number" step="any" value={form.co2_per_kg} onChange={e=>setForm({...form,co2_per_kg:e.target.value})}/></label><label>Water <small>CAD/m³</small><input required min="0" type="number" step="any" value={form.water_per_m3} onChange={e=>setForm({...form,water_per_m3:e.target.value})}/></label><label className="wide">Source / evidence<input required value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder="Utility tariff document or approved assumption"/></label><button className="primary wide">Save versioned tariff</button></form>{saved?<p className="saved">{saved}</p>:null}</article><aside className="panel policy"><span>POLICY</span><h2>Cost display guardrails</h2><ul><li>No default tariff values</li><li>Schedule presets contain no rates</li><li>Currency and units always visible</li><li>Effective date controls replay eligibility</li><li>Source retained for evidence</li><li>No savings claims in this diagnostic version</li></ul></aside></section>
}
